# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-22 03:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pugorugh', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdog',
            unique_together=set([('user', 'dog')]),
        ),
    ]
